name: Run command via SSH every day or on workflow dispatch
on:
  schedule:
    - cron: '0 0 * * *' # runs at 12:00 AM UTC every day
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run command via SSH
        run: |
          sudo apt update
          sudo apt install tmux -y
          mkdir /home/runner/.ssh || true
          touch id_sf-lulz-segfault-net
          cat >~/.ssh/id_sf-lulz-segfault-net ${{ secrets.id_sf }}
          cat >>~/.ssh/config ${{ secrets.config }}
          tmux new-session -d || tmux
          tmux new-session -d 'ssh usagechaos'
          tmux send-keys -t 0 "yes" Enter 'segfault'
          tmux send-keys -t 0 "N"
