name: Run command via SSH every day or on workflow dispatch
on:
  schedule:
    - cron: '0 0 * * *' # runs at 12:00 AM UTC every day
  workflow_dispatch:
env:
  SEGFAULT_TOKEN: ${{ secrets.SEGFAULT_TOKEN }}
jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            script.sh
      - name: Reboot Server
        run: |
          sudo apt update
          sudo apt-get install expect -y
          chmod +x restart.sh
          ./restart.sh ${{ secrets.SEGFAULT_TOKEN }}
      - name: Start Server
        run: |
          chmod +x script.sh
          ./script.sh ${{ secrets.SEGFAULT_TOKEN }}