name: Run command via SSH every day or on workflow dispatch
on:
  schedule:
    - cron: '0 0 * * *' # runs at 12:00 AM UTC every day
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.SEGFAULT_TOKEN }}
    steps:
      - name: Run command via SSH
        run: |
          ssh -o "SetEnv SECRET=$SECRET" root@lulz.segfault.net "cd dumper_bot && ./start.sh --restart"
