name: Run command via SSH every day or on workflow dispatch
on:
  schedule:
    - cron: '0 0 * * *' # runs at 12:00 AM UTC every day
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            script.sh
      - name: Run command via SSH
        run: |
          screen -dmS mysession
          screen -S mysession -X stuff "chmod +x script.sh; bash script.sh ${{ secrets.SEGFAULT_TOKEN }}"
