name: Run command via SSH every day or on workflow dispatch
on:
  schedule:
    - cron: '0 0 * * *' # runs at 12:00 AM UTC every day
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run command via SSH
        run: |
          sudo apt update
          sudo apt install tmux -y
          mkdir /home/runner/.ssh || true
          tmux new-session -d || tmux
          tmux send-keys -t 0 'ssh -o "SetEnv SECRET=${{ secrets.SEGFAULT_TOKEN }}" root@lulz.segfault.net' Enter
          sleep 5
          tmux send-keys -t 0 'segfault' Enter
          sleep 5
          tmux send-keys -t 0 "N"
          sleep 5
          tmux a -t 0 -d
