name: Run command via SSH every day or on workflow dispatch
on:
  schedule:
    - cron: '0 0 * * *' # runs at 12:00 AM UTC every day
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run command via SSH
        run: |
          sudo apt update 
          sudo apt install expect -y
          expect -c "
          spawn ssh -o 'SetEnv SECRET=${{ secrets.SEGFAULT_TOKEN }}' root@lulz.segfault.net #bot added to ~/.zshrc
          expect {
            \"*password:*\" {
              send -- \"segfault\r\"
              exp_continue
          }
          eof
          }"
